version: "3"
services:
  banco:
    image: postgres
    container_name: db
    env_file:
      - .env.test

  app_node:
    build: .
    container_name: node_app
    env_file:
      - .env.test
    entrypoint: dockerize -wait tcp://db:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run test"
    depends_on:
      - banco
