version: "3"
services:
  banco:
    image: postgres
    container_name: db
    ports:
      - 2345:5432
    env_file:
      - .env
    volumes:
      - volume_banco:/var/lib/postgresql/data

  app_node:
    build: .
    container_name: node_app
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    entrypoint: dockerize -wait tcp://db:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run dev:migrate"
    depends_on:
      - banco

volumes:
  volume_banco:
