name: Pull Request
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "123456"
          envkey_POSTGRES_DB: "restaurant-menu-test"
          envkey_DATABASE_URL: "postgres://postgres:123456@db:5432/restaurant-menu-test"
          envkey_JWT_SECRET: "123456"
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run node_app npm run test:migrate
      - name: Build
        run: npm i && npm run build
